# setting preferred bind key
unbind C-b
set-option -g prefix C-Space

# making the base index of windows and panes 1 for ease
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# make new panes open in the cwd
bind '"' split-window -v -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"

# settings up copy mode and movement keys to be more vim-like
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# changes escaping selection and quitting the action to be more vim-like (esc for both)
bind-key -T copy-mode-vi Escape if-shell -F "#{selection_present}" "send-keys -X clear-selection" "send-keys -X cancel"

# setting more intuitive binds for switching windows
bind -n M-H previous-window
bind -n M-L next-window

# installing tpm plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# installing colorscheme
set -g @plugin "arcticicestudio/nord-tmux"

# bootstrapping tpm
run '~/.tmux/plugins/tpm/tpm'
